### ISSUE TITLE
Magnetic declination

### ISSUE THREAD

**Issue by jeskesen** [richards-tech/RTIMULib#23]
Feature proposal:  Add the magnetic declination to RTIMUSettings (defaults to zero for current behavior) & subtract that value off when calculating earth-relative orientation.

Edit: I'm happy to do some or all of the work on this one.

**Comment by richardbarnett** [comment]
Not a bad idea - probably quicker and easier for me to do though.

**Comment by jeskesen** [comment]
sure thing.  just thought I'd offer.

**Comment by richardbarnett** [comment]
V5.3.0 has the feature now. Thanks for the suggestion.
