### ISSUE TITLE
QPose and ROS/IMU

### ISSUE THREAD

**Issue by tapiama** [richards-tech/RTIMULib#26]
Hi,

Thanks for the great library.  I'm using it with Adafruit's 9DoF IMU, and using the python API together with ROS (robot os).  I was able to read the IMU motions using roll, pitch, yaw as in your example.  Since I'm also trying to make it work with ROS - to generate ROS IMU messages, I'm also doing a bit of the following:

        if imu.IMURead():

            # get imu data
            data = imu.getIMUData()

            # publish imu in fusion pose quaternion, linear acceleration and angular velocity
            fusionQPoseValid = data["fusionQPoseValid"]
            gyroValid = data["gyroValid"]
            accelValid = data["accelValid"]
            if fusionQPoseValid and gyroValid and accelValid:
                fusionQPose = data["fusionQPose"]
                accel = data["accel"]
                gyro = data["gyro"]
                imu_result = Imu()
                imu_result.header = Header()
                imu_result.header.stamp= rospy.Time.now()
                imu_result.header.frame_id = frame_id
                imu_result.orientation = Quaternion()
                imu_result.orientation.w = fusionQPose[0]
                imu_result.orientation.x = fusionQPose[1]
                imu_result.orientation.y = fusionQPose[2]
                imu_result.orientation.z = fusionQPose[3]
                imu_result.linear_acceleration = Vector3()
                imu_result.linear_acceleration.x = accel[0]
                imu_result.linear_acceleration.y = accel[1]
                imu_result.linear_acceleration.z = accel[2]
                imu_result.angular_velocity = Vector3()
                imu_result.angular_velocity.x = gyro[0]
                imu_result.angular_velocity.y = gyro[1]
                imu_result.angular_velocity.z = gyro[2]
                imu_pub.publish(imu_result)

It appear to work when I tried to visualize it using ROS/rviz and moving the IMU using above generated message, but pitch (read as quaternion) is inverted, and when I visual acceleration gravity is going up instead of down. Yaw is also strange - it move in the direction of IMU's movement but then it drift back to initial value in ~1 sec.  Roll appear to be in the right direction when I move the IMU from side to side..

I apologize I am not well versed in 3D math, especially about quaternion.  Am I reading the wrong API, or is my IMU mounted up-side-down.. Any suggestions would be greatly appreciated!! :)

Bill

**Comment by richardbarnett** [comment]
I didn't understand what "pitch (read as quaternion)" meant. How are you generating the roll, pitch and yaw? You can obtain that from the fusionPose variable, fusionPose[0] is roll, fusionPose[1] is pitch and fusionPose[z] is yaw.

If your IMU is mounted in a different position from the library's reference, then you will see different results. You can tell the software of a different orientation - see this link for details: https://richardstechnotes.wordpress.com/2014/11/18/rtimulib-now-supports-imu-axis-rotation/. 

As for yaw reverting, this suggests that the magnetometer isn't working. Check the compass array variable to check that the values are non-zero and varying.
