### ISSUE TITLE
Settings object needs to be kept in scope?

### ISSUE THREAD

**Issue by stewartmurrie** [richards-tech/RTIMULib#27]
This may expose my lack of understanding about how objects work in Python, but here goes.

I wrote some code based on the Fusion.py example, but decided to modularize it a bit by having the initialization code in one function (the part between ```SETTINGS_FILE=...``` and ```poll_interval =...```), with another function called in my main loop to read IMU data. My init function returns the imu reference into the main loop so that I can call ```imu.IMURead()``` on it. However, I discovered that ```IMURead()``` always returns ```False``` in this setup. The only way I could get it to work is if I my init function *also* returns a reference to the settings object, which is then retained (but never used) in my main loop. It seems that, if the settings object is allowed to go out of scope when my init function returns, then the IMU can no longer be read.

Is this expected behaviour? Am I missing something obvious about object scope in Python? I can see in the library code that a reference to the settings object does get cached by ```RTIMU::RTIMU(RTIMUSettings *settings)``` but that doesn't seem to keep it alive if it goes out of scope on the Python side. What's going on here?

**Comment by richardbarnett** [comment]
You are correct - you can't let the settings object go out of scope on the Python side. The settings object isn't just used at creation - it is used in operation also. So it needs to be kept around with the IMU object. Possibly not ideal but it will at least work if you do that!
