### ISSUE TITLE
undefined reference MS5611

### ISSUE THREAD

**Issue by luks3n** [richards-tech/RTIMULib#28]
Found a bug in newest version :
objects/RTPressure.o: In function `RTPressure::createPressure(RTIMUSettings*)':
RTPressure.cpp:(.text+0xe4): undefined reference to `RTPressureMS5611::RTPressureMS5611(RTIMUSettings*)'
collect2: ld returned 1 exit status

I am using a MPU9250 on SPI. The pressure sensor shouldn't cause any problems because MPU9250 does not have a pressure sensor anyway, right? Probably has something to do with the March 21 release, where support for MS5611 was added.

**Comment by richardbarnett** [comment]
Which way are you building things? Makefile, CMakeLists...? In fact, what are you trying to build?

**Comment by luks3n** [comment]
I build via makefile on Raspberry Pi, but it's one of my own projects, which uses a configuration file generated by RTIMULibCal (was generated before the update). Up until I updated today it compiled just fine, now this happens.

**Comment by richardbarnett** [comment]
You probably need to add RTPressureMS5611.cpp to your Makefile then. It needs to compiled and linked in whether you eventually use it or not.

**Comment by luks3n** [comment]
True, I thought I autocompiled everything that is in the RTIMULib directory, guess it wasn't. Solved.
