### ISSUE TITLE
Missing version in SONAME

### ISSUE THREAD

**Issue by XECDesign** [richards-tech/RTIMULib#37]
I'm currently packaging up RTIMULib for inclusion in Raspbian and the Debian folk consider RTIMULib.so broken, since it doesn't have a proper SONAME.

More information here:
https://www.debian.org/doc/debian-policy/ch-sharedlibs.html
https://lintian.debian.org/tags/sharedobject-in-library-directory-missing-soname.html

Not a really an issue for our purposes, but thought it was worth reporting anyway.

**Comment by richardbarnett** [comment]
Thanks for that. I'll take care of it.

**Comment by richardbarnett** [comment]
There's now a V7.0.1 that should fix that for the CMake build but were you actually referring to the Python extension library?

**Comment by XECDesign** [comment]
Thanks. I didn't get to the python part yet, so I'm not sure what will be needed there.

**Comment by XECDesign** [comment]
Whoops, something is wrong.
```
~/dev/RTIMULib/RTIMULib/build $ readelf -d libRTIMULib.so | grep SONAME
 0x0000000e (SONAME)                     Library soname: [libRTIMULib.so]
```
Looking at the commit history, it seems like you've removed the version variables from RTIMULib/CMakeLists.txt in 6242504b08a9ec322e868594adf4cdeb10a9b4e1

**Comment by richardbarnett** [comment]
I moved the version defs out to the main Linux CMakeLists.txt. I guess that's given you a problem. I'll put it back the way it was.

**Comment by XECDesign** [comment]
No wait, I forgot that there was the main one. It's probably better for me to use that one. But if someone does build using the cmake files in rtimulib subdirectory, they'll get a slightly different  .so, which seems a little problematic.

**Comment by richardbarnett** [comment]
I am certainly not a CMake expert so I wasn't sure what was the best thing to do here. It should be ok to just build the library and have it work the same. I just want to make sure that a consistent version number is applied (there is also an OpenGL lib - that's what caused the issue). I think that a better approach would be to include a file that contains the version info so that it works in all cases.

**Comment by XECDesign** [comment]
Yeah, that sounds like a good approach.

On an unrelated side note. I saw that you were thinking about adding IIO support. If I managed to write IIO drivers for the devices we need, this was actually going to be my next PR. So it's definitely a +1 from me.

**Comment by richardbarnett** [comment]
Ok. Let me know what I can do to help with that.

**Comment by richardbarnett** [comment]
V7.0.3 should hopefully handle the CMake version correctly now!

**Comment by XECDesign** [comment]
Seems okay, thank you.
