### ISSUE TITLE
libRTIMULib.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by cyborg-x1** [richards-tech/RTIMULib#41]
I am now getting this error, after I recompiled and installed your library with the latest changes from you and my change. 
RTIMULibDemo: error while loading shared libraries: libRTIMULib.so.7: cannot open shared object file: No such file or directory

**Comment by richardbarnett** [comment]
Run:

sudo ldconfig

**Comment by cyborg-x1** [comment]
Ah thanks,  	
Another one for "you live and learn".
